using Ganss.Xss;

namespace WarbandOfTheSpiritborn.Services
{
    public class HtmlSanitizationService : IHtmlSanitizationService
    {
        private readonly HtmlSanitizer _aboutSanitizer;
        private readonly HtmlSanitizer _blogSanitizer;

        public HtmlSanitizationService()
        {
            _aboutSanitizer = CreateAboutSanitizer();
            _blogSanitizer = CreateBlogSanitizer();
        }
        private static HtmlSanitizer CreateAboutSanitizer()
        {
            var sanitizer = new HtmlSanitizer();

            // Start with no permissions from the package defaults.
            sanitizer.AllowedTags.Clear();
            sanitizer.AllowedAttributes.Clear();
            sanitizer.AllowedCssProperties.Clear();
            sanitizer.AllowedAtRules.Clear();
            sanitizer.AllowedSchemes.Clear();
            sanitizer.UriAttributes.Clear();

            // Preserve only the HTML produced by the About Quill toolbar.
            sanitizer.AllowedTags.UnionWith(new[]
            {
                "p",
                "br",
                "h1",
                "h2",
                "h3",
                "strong",
                "em",
                "u",
                "ol",
                "ul",
                "li",
                "blockquote",
                "a"
             });

            // Links need href; event attributes such as onclick remain forbidden.
            sanitizer.AllowedAttributes.Add("href");
            sanitizer.UriAttributes.Add("href");

            // Only permit safe link schemes.
            sanitizer.AllowedSchemes.Add("http");
            sanitizer.AllowedSchemes.Add("https");
            sanitizer.AllowedSchemes.Add("mailto");

            return sanitizer;
        }
        private static HtmlSanitizer CreateBlogSanitizer()
        {
            var sanitizer = new HtmlSanitizer();

            sanitizer.AllowedTags.Clear();
            sanitizer.AllowedAttributes.Clear();
            sanitizer.AllowedCssProperties.Clear();
            sanitizer.AllowedAtRules.Clear();
            sanitizer.AllowedSchemes.Clear();
            sanitizer.UriAttributes.Clear();
            sanitizer.AllowedClasses.Clear();

            sanitizer.AllowedTags.UnionWith(new[]
            {
                "p",
                "br",
                "h1",
                "h2",
                "h3",
                "strong",
                "em",
                "u",
                "s",
                "ol",
                "ul",
                "li",
                "blockquote",
                "pre",
                "a"
            });

            sanitizer.AllowedAttributes.UnionWith(new[]
            {
                "href",
                "class"
            });

            sanitizer.UriAttributes.Add("href");

            sanitizer.AllowedSchemes.UnionWith(new[]
            {
                "http",
                "https",
                "mailto"
            });

            // Preserve only classes generated by supported Quill formats.
            sanitizer.AllowedClasses.UnionWith(new[]
            {
                "ql-syntax",
                "ql-align-center",
                "ql-align-right",
                "ql-align-justify"
            });

            return sanitizer;
        }
        public string SanitizeAbout(string? html)
        {
            return Sanitize(_aboutSanitizer, html);
        }
        
        public string SanitizeBlog(string? html)
        {
            return Sanitize(_blogSanitizer, html);
        }

        private static string Sanitize(HtmlSanitizer sanitizer, string? html)
        {
            if (string.IsNullOrWhiteSpace(html))
            {
                return string.Empty;
            }

            return sanitizer.Sanitize(html);
        }
    }
}
